---
title: "Una revisión de los efectos de los cambios ambientales antropogénicos en las interacciones tróficas de los ecosistemas marinos en el gradiente latitudinal Atlántico Sudoccidental - Antártida: una aproximación mediante redes ecológicas"
author: "Tomás I. Marina & Leonardo A. Saravia"
output: word_document
bibliography: "MS_Anales.bib"
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```


## RESUMEN

## INTRODUCCIÓN

Las redes ecológicas están compuestas por un conjunto de especies y/o grupos funcionales y conexiones que representan las interacciones y los flujos de energía y/o materia en un sistema. Particularmente, una red ecológica describe las interacciones entre especies en una comunidad y hábitat determinados. En los ecosistemas ocurren interacciones de diferentes tipos: tróficas (de alimentación), mutualistas (de provisión de alimento y refugio), competitivas (de interferencia en la utilización de los recursos comunes), entre otras. Esta aproximación al estudio de las comunidades como una red de múltiples interacciones es una herramienta de análisis que ayuda a revelar no sólo la estructura y estabilidad sino las propiedades dinámicas y energéticas de un ecosistema [@Belgrano2005]. Los modelos tróficos de redes complejas pueden ser útiles para evitar el reduccionismo de analizar solo las especies que se suponen importantes y/o con las interacciones de mayor flujo relativo, lo que trae como consecuencia una descripción sesgada e incompleta del sistema en estudio. Al incorporar la mayor parte de las interacciones es posible capturar fenómenos emergentes imposibles de predecir cuando se utilizan modelos de pocas especies [@Hagstrom2017]. Esto proporciona una perspectiva de sistemas complejos para investigar los fenómenos ecológicos y para analizar los efectos del cambio climático global y las perturbaciones antropogénicas en los ecosistemas marinos [@Pascual2005].

El estudio de la complejidad, estructura y estabilidad de las redes tróficas utilizando la teoría de redes comenzó en la década de 1970 con el análisis de comunidades terrestres y dulceacuícolas [@May1973; @Cohen1978; @Pimm1980; @Briand1987]. Durante esta época, el físico australiano Robert M. May sugirió, de manera teórica, que existía una relación entre complejidad, analizada mediante la conectividad (C = L/S^2 donde L es el número de interacciones y S es el número de especies), y estabilidad en redes tróficas: a mayor complejidad, menor estabilidad [@May1973]. Con el advenimiento de redes tróficas empíricas de mayor resolución, es decir mayor representación de especies biológicas que de grupos funcionales agregados y, por ende, complejidad, la hipótesis sobre la relación entre complejidad y estabilidad comenzó a ser objeto de debate [@Martinez1993; @Hall1997; @Jacquet2016]. Actualmente, los estudios de redes tróficas se centran en el análisis de la estructura y su influencia en el funcionamiento y estabilidad de los ecosistemas [e.g. @Stouffer2011; @Marina2018; @Marina2018a; @Landi2018]. En este sentido, existe evidencia de correlación entre ciertas propiedades estructurales y la respuesta de las redes tróficas a cambios de diverso origen afectando, en última instancia, la estabilidad de la red [@Stouffer2011; @Johnson2014; @Borrelli2015].

En particular, las contribuciones realizadas con respecto a la complejidad, estructura y estabilidad de las redes tróficas marinas utilizando el enfoque de redes complejas se concentran en algunos ecosistemas. Los ecosistemas marinos más estudiados en este sentido son: el Mar Báltico [@Yletyinen2016; @Kortsch2021; @Tomczak2022], el Mar de Barents [@Olivier2017], el intermareal rocoso de Chile [@Perez-Matus2017] y algunas regiones costeras antárticas y pelágicas del Océano Austral [@Jacob2011; @Ortiz2017; @Rossi2019; @McCormack2020]. A modo de resumen, estos trabajos dan evidencia de la existencia de una compleja red de interacciones tróficas con características estructurales particulares en cada sistema estudiado. Sin embargo, se pueden destacar algunas generalidades para las redes tróficas marinas: 1) distribución asimétrica de las interacciones, es decir que la mayoría de las especies están poco conectadas mientras que una minoría concentra las interacciones; 2) alto porcentaje de especies omnívoras (> 40%); y 3) organización en módulos, donde un subgrupo de especies está más conectado entre sí que con el resto de las especies de la red. En su mayoría, estos avances fundamentales en el conocimiento de la ecología trófica de los ecosistemas se han realizado utilizando redes tróficas cualitativas, donde solo la presencia/ausencia de la interacción se tuvo en cuenta para la construcción y análisis de la red.

Uno de los cambios ambientales más importantes en los ecosistemas marinos de altas latitudes es el aumento de la temperatura superficial media del agua [@Bulgin2020; @Gutt2021], registrándose incrementos de hasta 1ºC en los últimos 50 años [@Meredith2005]. Uno de los principales efectos directos sobre las especies marinas es el cumanto de la demanda metabólica [@Brown2004] y el cambio de distribución de las especies, que trae como consecuencia extinciones y/o invasiones locales particularmente en los ecosistemas de aguas templado-frías [e.g. @Kortsch2015; @McCarthy2019]. Por otro lado, uno de los cambios antropogénicos históricamente determinantes para la estructura y funcionamiento de los ecosistemas marinos ha sido y es la actividad pesquera [@Halpern2007]. Además del efecto directo sobre la biomasa de la especie objetivo de la pesca, se ha evidenciado que las pesquerías alteran la dieta y preferencia de los depredadores mediante la captura incidental y/o el descarte [@Funes2019].

## CAMBIOS AMBIENTALES ANTROPOGÉNICOS EN EL ATLÁNTICO SUDOCCIDENTAL Y LA PENÍNSULA ANTÁRTICA

Los efectos de los cambios ambientales antropogénicos en los ecosistemas del Atlántico Sudoccidental, particularmente del Mar Argentino, y la Península Antártica han sido estudiados principalmente con foco en una única especie o en un grupo reducido de especies de interés [e.g. @Dans2021; @Almandoz2019; @Fioramonti2022; @Sahade2015]. A continuación se describe el estado de conocimiento de los efectos de los cambios ambientales antropogénicos en diferentes ecosistemas marinos que en su conjunto comprenden un gradiente latitudinal en el rango 45º S - 62º S (Fig. 1).

### SITUACIÓN EN EL GOLFO SAN JORGE

### SITUACIÓN EN EL AMP NAMUNCURÁ - BANCO BURDWOOD

### SITUACIÓN EN EL CANAL BEAGLE

### SITUACIÓN EN CALETA POTTER (ANTÁRTIDA)


## ¿CUÁL HA SIDO EL APORTE DESDE LA APROXIMACIÓN DE REDES ECOLÓGICAS?

## PERSPECTIVAS A FUTURO

Proponemos las siguientes perspectivas como ejes de investigación para mejorar la comprensión de los efectos de los cambios ambientales antropogénicos en ecosistemas marinos del gradiente latitudinal Atlántico Sudoccidental - Antártida:

1. Incluir información sobre la intensidad de interacción

En las últimas décadas se ha puesto énfasis en el rol que cumple la intensidad de interacción como un aspecto fundamental para mejorar la comprensión de la estructura de las redes tróficas y su influencia en la estabilidad en ecosistemas sometidos a perturbaciones de diverso origen [@Neutel2007; @Shurin2012; @Nilsson2016; @Kortsch2021]. Sin embargo, la mayoría de los estudios de simulación de efectos de cambios ambientales antropogénicos realizados en redes tróficas empíricas de alta resolución utilizan redes cualitativas, es decir que solo tienen en cuenta la presencia/ausencia de las interacciones y no su intensidad [@Dunne2002; @Byrnes2007; @Eklof2013; @Cordone2018]. Por otro lado, aquellos estudios que estiman la intensidad de interacción entre las especies, obteniendo redes tróficas cuantitativas, sugieren que el rol de las interacciones débiles o de menor intensidad relativa es esencial para proveer estabilidad a la red [@Emmerson2004; @Bascompte2005; @vanAltena2016].

2. Evaluar la posibilidad de cambios de régimen

Con el advenimiento de ecosistemas marinos sometidos a múltiples perturbaciones simultáneamente (aumento de temperatura, pesquerías) [@Dans2021; @Gutt2021], es posible que se desencadenen cambios de régimen o de estructura en el entramado de múltiples interacciones tróficas. Un cambio de régimen en un ecosistema puede definirse como la ocurrencia de cambios relativamente abruptos entre estados persistentes que pueden presentarse en un sistema complejo [@deYoung2008]. Generalmente estos cambios se producen a nivel local pero pueden propagarse espacialmente hasta comprender regiones extensas [@Eklof2020]. La conexión entre los cambios de régimen entre diferentes áreas puede darse debido a la dispersión de especies. Si los organismos se dispersan entre áreas locales, el cambio debería comenzar en las áreas donde los sistemas están más cerca de los umbrales de transición, propagándose gradualmente hacia otras áreas como un efecto dominó [@Leemput2015]. La mayor interconexión entre cambios de régimen fue encontrada en ecosistemas marinos en estudios que involucran comunidades de macroalgas, fenómenos de eutroficación o el colapso de pesquerías [@Rocha2018]. Esto subraya la importancia de analizar las conexiones entre los posibles cambios de régimen en el gradiente latitudinal Atlántico Sudoccidental - Antártida.

## AGRADECIMIENTOS

## LITERATURA CITADA